// <auto-generated />
using System;
using BackendAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251031102400_ChangedColorThemeFromUserToConversation")]
    partial class ChangedColorThemeFromUserToConversation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("ColorTheme")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            ConversationId = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "General"
                        },
                        new
                        {
                            ConversationId = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tech Talk"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.ConversationMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<string>("ColorTheme")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMembers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ConversationId = 1,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 1,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 2,
                            ConversationId = 2,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.DbTest", b =>
                {
                    b.Property<int>("DbTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbTestId"));

                    b.Property<string>("testString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DbTestId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            DbTestId = 1,
                            testString = "Test!!!"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ConversationId = 1,
                            MessageContent = "Hello everyone!",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ConversationId = 1,
                            MessageContent = "Hi Alice!",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ConversationId = 2,
                            MessageContent = "Anyone tried .NET MAUI?",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            Password = "$2a$11$DHb2SBahkIIXSIv1hf.GX.fP1BjCtOwTJJ9Boyqi3PrjEqCZRQs66",
                            ProfilePicture = "alice.png",
                            Username = "alice"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            Password = "hashed_pw_2",
                            ProfilePicture = "bob.png",
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.ConversationMember", b =>
                {
                    b.HasOne("BackendAPI.Models.Conversation", "Conversation")
                        .WithMany("UserList")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", "User")
                        .WithMany("MemberIn")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.Models.Message", b =>
                {
                    b.HasOne("BackendAPI.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.Models.Conversation", b =>
                {
                    b.Navigation("UserList");
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Navigation("MemberIn");
                });
#pragma warning restore 612, 618
        }
    }
}
