// <auto-generated />
using System;
using BackendAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20250925132002_DummyDataWithTimezone")]
    partial class DummyDataWithTimezone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendAPI.Models.Chatroom", b =>
                {
                    b.Property<int>("ChatroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatroomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChatroomId");

                    b.ToTable("Chatrooms");

                    b.HasData(
                        new
                        {
                            ChatroomId = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "General"
                        },
                        new
                        {
                            ChatroomId = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tech Talk"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.ChatroomMember", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ChatroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ChatroomId");

                    b.HasIndex("ChatroomId");

                    b.ToTable("ChatroomMembers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ChatroomId = 1,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            ChatroomId = 1,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            ChatroomId = 2,
                            JoinedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ChatroomId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatroomId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChatroomId = 1,
                            MessageContent = "Hello everyone!",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ChatroomId = 1,
                            MessageContent = "Hi Alice!",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ChatroomId = 2,
                            MessageContent = "Anyone tried .NET MAUI?",
                            TimeStamp = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@example.com",
                            PassWord = "hashed_pw_1",
                            ProfilePicture = "alice.png",
                            Username = "alice"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@example.com",
                            PassWord = "hashed_pw_2",
                            ProfilePicture = "bob.png",
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("Test.DbTest", b =>
                {
                    b.Property<int>("DbTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbTestId"));

                    b.Property<string>("testString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DbTestId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            DbTestId = 1,
                            testString = "Test!!!"
                        });
                });

            modelBuilder.Entity("BackendAPI.Models.ChatroomMember", b =>
                {
                    b.HasOne("BackendAPI.Models.Chatroom", "Chatroom")
                        .WithMany("UserList")
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", "User")
                        .WithMany("MemberIn")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.Models.Message", b =>
                {
                    b.HasOne("BackendAPI.Models.Chatroom", "Chatroom")
                        .WithMany()
                        .HasForeignKey("ChatroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendAPI.Models.Chatroom", b =>
                {
                    b.Navigation("UserList");
                });

            modelBuilder.Entity("BackendAPI.Models.User", b =>
                {
                    b.Navigation("MemberIn");
                });
#pragma warning restore 612, 618
        }
    }
}
