// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test;

#nullable disable

namespace BackendAPI.Migrations
{
    [DbContext(typeof(MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test.DbTest", b =>
                {
                    b.Property<int>("DbTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DbTestId"));

                    b.Property<string>("testString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DbTestId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            DbTestId = 1,
                            testString = "Test!!!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
