

@startuml

Frontend -> AuthController: HTTP POST request
AuthController -> AuthController : Login(loginDto)
AuthController -> AuthService: LoginAsync(loginDto)
AuthService -> AuthService: LoginAsync(loginDto)
AuthService -> AuthRepository: PostLoginAsync(loginDto)
activate AuthRepository
AuthRepository -> AuthRepository: PostLoginAsync(loginDto)
AuthRepository --> AuthService: User
deactivate AuthRepository
AuthService -> PasswordHasher: VerifyPassword(loginDto.Password, user.Password)
activate PasswordHasher
PasswordHasher --> AuthService: true
deactivate PasswordHasher
AuthService -> IConfiguration: Get("Jwt: Secret")
activate IConfiguration
IConfiguration --> AuthService: secretKey
deactivate IConfiguration
AuthService -> AuthService: Perform Auth
AuthService --> AuthController: securityToken
AuthController --> Frontend: Ok(token)
Frontend -> UserController: HTTP GET request
activate UserController
UserController -> UserController: GetUserById(id)
UserController -> UserService: GetUserByIdAsync(id)
deactivate UserController
activate UserService
UserService -> UserService: GetUserByIdAsync(userId)
UserService -> UserRepository: GetByIdAsync(userId)
deactivate UserService
activate UserRepository
UserRepository -> UserRepository: GetByIdAsync(userId)
UserRepository --> UserService: User
deactivate UserRepository
UserService --> UserController: UserDto
UserController --> Frontend: OK(UserDto)


@enduml
